proper pre-clean and option processing
Signed-off-by: nixnodes <code@nixnodes.net>

diff --git a/scripts/common b/scripts/common
--- a/scripts/common
+++ b/scripts/common
@@ -170,8 +170,9 @@ git_pull()
 	save_path=${PWD}
 	cd ${BASE_PATH}
 	${GIT} pull git://${1}/nixnodes/zonebuild ${2}
+	git_exit=$?
 	cd ${save_path}
-	return $?
+	return ${git_exit}
 }
 
 script_get_vr()
@@ -202,6 +203,24 @@ get_opt()
 		}
 	done
 	return 1
+}
+
+TIERS_CLEANED=()
+
+#[1]: tier
+clean_on_enter()
+{
+	[[ "${1}" != tier[012] ]] && {
+		echo "${0}: invalid tier: ${1}"
+		return 1
+	}
+	[[ "${TIERS_CLEANED[@]}" = *"${1}"* ]] && {
+		echo "${0}: ${1} was already cleaned, skipping.."
+		return 0
+	}
+	rm -f "${OUT_PATH}/${1}/*.db" "${OUT_PATH}/${1}/*.conf" || return 1
+	TIERS_CLEANED+=("${1}")
+	return 0
 }
 
 script_join_verstring()
diff --git a/scripts/config b/scripts/config
--- a/scripts/config
+++ b/scripts/config
@@ -69,14 +69,19 @@ SYNC_SERVERS=(  "mtn://172.22.177.77/?net.dn42.registry"
 BASE_PATH=`dirname ${0}`
 ##
 
+PROC_OPTIONS=()
+
 OPTION_HOOKS=(
-	"[[ \"\${@}\" = *-update*  ]] && {
-		git_pull \${GIT_ADDRESS} ${GIT_BRANCH}
-		\${0} \`echo \${@} | sed -r 's/\-update//g'\`
-		exit \$?
-	}"
+	'[[ "${arg}" = "-update"  ]] && {
+		if git_pull ${GIT_ADDRESS} ${GIT_BRANCH}; then
+			${0} `echo ${@} | sed -r "s/\\-update//g"`
+		else
+			echo "${0}: git pull failed"
+		fi
+		exit $?
+	}'
 	
-	'[[ "${@}" = *-config*  ]] && {
+	'[[ "${arg}" = "-config"  ]] && {
 		int_opt="-config"
 		NCONF=`get_opt "${@}"` 
 		if [ -f "${BASE_PATH}/${NCONF}" ]; then
@@ -85,11 +90,15 @@ OPTION_HOOKS=(
 			echo "${0}: ${BASE_PATH}/${NCONF} not found"
 			exit 2
 		fi
-	}'	
+	}'
+	
+	'[[ "${arg}" = "root" ]] && PROC_OPTIONS+=(1)'
+	'[[ "${arg}" = "zone" ]] && PROC_OPTIONS+=(2)'
+	'[[ "${arg}" = "arpa" ]] && PROC_OPTIONS+=(3)'
+	'[[ "${arg}" = "res" ]] && PROC_OPTIONS+=(4)'
 )
 
-PRE_BUILD_HOOKS=(	
-
+PRE_BUILD_HOOKS=(
 	'[ ${PULL_BEFORE_BUILD} -gt 0 ] && {
 		! [ -f ${REGISTRY_BASE_PATH}/r.db ] && {
 			rm -Rf ${REGISTRY_BASE_PATH}/net.dn42.registry
